export const ARABIC = {
  PLANS: "الخطط",
  NAME: "الإسم",
  ENTER_A_NAME: "أدخل اسم",
  AGE: "العمر",
  DESCRIBTION: "الوصف",
  ENTER_A_DESCRIPTION: " أدخل وصف [اختياري]",
  EXCERCISE: "التمرين",
  EXCERCISES: "التمارين",
  SAVE: "حفظ",
  CANCEL: "إلغاء",
  CONFIRM: "تأكيد",
  ADD_EXCERCISE: "إضافة تمرين",
  ADD_EXCERCISE_HERE: " أضف تمارين هنا",
  ENTER_NOTES: " أدخل الملاحظات [اختياري]",
  EDIT: "تعديل",
  DELETE: "حذف",
  NOTES: "ملاحظات",
  HI: "مرحبا",
  CREATE_A_PLAN: "إنشاء خطة",
};

export const ENGLISH = {
  CREATE: "Create",
  PLANS: "Plans",
  NAME: "Name",
  ENTER_A_NAME: "Enter a name",
  AGE: "Age",
  DESCRIBTION: "Description",
  ENTER_A_DESCRIPTION: "Enter a description [Optional]",
  EXERCISE: "Exercise",
  EXCERCISES: "Exercises",
  SAVE: "Save",
  CANCEL: "Cancel",
  CONFIRM: "Confirm",
  ADD_EXERCISE: "Add Exercise ",
  ADD_EXERCISE_HERE: "Add Exercises Here",
  ENTER_NOTES: "Enter Notes [Optional]",
  EDIT: "Edit",
  DELETE: "Delete",
  NOTES: "Notes",
  HI: "Hi",
  CREATE_A_PLAN: "Create a Plan",
};
